### ISSUE TITLE
（非校对）通关后对翻译的一点小建议

### ISSUE THREAD

**Issue by heterojunction** [ToadStudio/sakuranotoki_trail_chs#4]
首先十分感谢汉化。
只是想玩游戏，于是下载了补丁玩了一下。并不是校对，因为根本不懂日语，只能在我一眼就能看出来的遣词造句和名词上稍微可以优化一下的地方给点建议。
版本没注意，所以可能已经改掉了。

“讯问”与“询问”：
静流询问直哉时，不妨将几句中的用词区别“询问”与“讯问”以求表达效果。

文化財可以译作“文化遗产”。

荒練り的对应中文讲法貌似是“羊角揉”，参考：
https://neriage.jp/kiso/kiso4.html
https://www.bilibili.com/video/BV1Wt411R7aR?from=search&seid=7218939979482856273&spm_id_from=333.337.0.0

教头建议翻译成教导主任，否则像在看水浒传。

静流与丽华在咖啡馆见面的时候对话中有“有一个叫圭的女孩”，疑似这一段静流也把圭当成女孩了。

一蓮托生我认为翻译成“一衣带水”不太恰当，可以翻译为“休戚与共”“唇齿相依”，俗一点“一条绳上的蚂蚱”也可以。（纱希带真琴卖花瓶时的对话）

助手研究员/助理研究员（Assistant Researcher）是聘任教师的一种，建议翻译成研究助理（Research Assistant），更符合临时访问，没有学位，主要在研究室中帮忙的鸟谷静流的身份。

Olympia的作者是爱德华·马奈，在健一郎与静流的对话中被写成了莫奈。

**Comment by Sicanus** [comment]
感谢长篇反馈。

其实我在翻译的时候也在很多遣词造句的地方犹豫了很久。最早我的确是翻译为主任而不是按照原文抄下来的教头，但汉化进行到最后几个文件时发现沙希真的当过“主任”（原文），为了加以区分又把前面翻译的主任改回了教头。

文化财方面，似乎是日本的一个独特叫法，维基百科中文页面也是这样写的。（参见：https://zh.wikipedia.org/zh-hans/%E6%97%A5%E6%9C%AC%E6%96%87%E5%8C%96%E8%B4%A2?wprov=sfla1 ）我认为改为文化遗产不太合适，才未作修改。

关于羊角揉和圭的错误已经在过去几天中修正。

而其余所提到的问题，我也会再次与原文进行对照后进行修改/优化。

最后再次感谢dalao的细心发现与建议。
此致

**Comment by heterojunction** [comment]
感谢您的回复！贵组对待汉化的认真态度让不懂日语又喜欢钦点的本人自叹弗如x
咨询了有经验的群友，“教头”可以被认为是“校长助理”。
“文化财”确实不一样，学到了，感谢。
![Uploading -17bef73626b0c3b8.jpg…]()

**Comment by heterojunction** [comment]
或者
校长办公室主任
学校幕僚长
学务长
教务主任
↑以上是群友的建议，我们也不确定，仅供参考。

**Comment by Sicanus** [comment]
多谢提供建议。

dalao的建议现已整合进入汉化补丁。
