### ISSUE TITLE
一些词句翻译的修改建议

### ISSUE THREAD

**Issue by robinzhang24** [ToadStudio/sakuranotoki_trail_chs#5]
这两天在玩体验版的时候正好找到了你们的汉化，非常感谢大佬们的贡献！我在游玩的过程中注意到了一些翻译中可以优化的部分，大部分都是遣词造句的微小差异，基本都是玩游戏的时候听语音听到的，没有语音的部分就没检查了（就是懒），然后后半段剧情高潮的部分也光顾着看剧情了没怎么比对，加上日语下手，多有疏漏还请谅解。对应的文档编号和block都标注了：

01023-224：気難しい，神经质->怪癖（静流酱不是说精神上敏感，应该是性格怪癖这种）
01024-117：是的。夏目氏原本统帅着名为「夏目一家」的黑帮组织，虽然现在已经解散了。
01024-152：这是个哪怕只剩下一秒钟也能够一转攻势的大招，但我从没想过我我真的会在实战中使用它。（原文是ぎゃくてん，但是果然还是想翻得生草一点w）
01024-161：只是自卫的程度而已。
01024-166：suruchin->棕榈镇。https://shop.ryukyukobudo.net/item/suruchin/ 在这个网站上看到的，虽然日语里总是写假名但是翻译的话这个应该比罗马音要好些吧
01024-169：精通剑道者所持的木刀才是格外令人胆寒的武器。（桁違い强调一种格外，差距悬殊的意思）
01025-036：罗马音改成平假名或者片假名会好点？
01031-095：中村家愿意给你们好脸色看，所以你能像这样无忧无虑地烧着陶器。

大佬们斟酌一下有无修改必要吧~

另外，虽然我在程序方面几乎毫无经验，但是对这个体验版的解包和汉化实现原理很感兴趣。大佬们能否给些指点？

**Comment by robinzhang24** [comment]
对了，关于ル・マルサール・ルザルツ我也基本是毫无头绪，https://arca.live/b/yuzusoft/36184150?mode=best 这个blog里面貌似提供了一些思路，个人推测应该是法语，マルサール->moselle，流经法国北部的河流，最早的软质瓷器就是在那一带制作的

**Comment by Sicanus** [comment]
@robinzhang24 
感谢指正。

由于当时翻译得过快，的确是疏忽了很多地方。所提及之处现已被修改。但01025-036处的罗马音未作修改，因为考虑到汉化的目标群体是对日语一无所知的人，所以只能使用全世界人民都看得懂的拉丁字母来表音而不能用假名。

关于ル・マルサール・ルザルツ的这份考据似乎是在翻译工作完成后才有的，翻译作业时网上没有任何相关的资料。不过这份考据的准确度仍然存疑，我自己对法语也缺乏深入了解（虽然在德国上学，但几乎完全不懂法语（悲）），所以暂时不做修改。

至于解包相关的问题，这次枕社没做任何加密，而且把所有的内容都打包到了唯一一个pfs文件里面，用GARbro一类的工具可以很容易地进行提取。提取出来所有文件都无需做任何处理就能使用（文本不但没加密还用的UTF-8编码，连改变编码和字体的功夫都省了），因此这次的汉化工作才能省去折腾程序的步骤直接对文本下手。
