### ISSUE TITLE
关于樱之刻第二章体验版的汉化问题

### ISSUE THREAD

**Issue by kisakichan** [ToadStudio/sakuranotoki_trail_chs#6]
大佬是否有意愿继续做第二章的汉化呢？

**Comment by Sicanus** [comment]
还没玩（主要是似乎和第一章不一样，第二章并不是公开的资源，下载渠道找不到不说（百度网盘没会员QAQ），而且再像前一次一样公开分享可能会面临法律问题（人在EU，还是很怕欧盟的神仙版权保护的））

但如果我玩上了了的话大概率还是会做，届时请务必再次合作：）（不过这一次我大概就只会分享补丁本身了，游戏本体+补丁等就劳烦大佬等人分享吧）

（小小的请求：要是大佬有本体的资源可以上传到Google Drive或OneDrive等平台后邮件分享给我吗（codemonkey01@protonmail.com）？百度网盘毕竟十年不用一回给李叔叔交钱总觉得心疼）

**Comment by kisakichan** [comment]
邮件已经发过去啦，这次的第二章我也是今天才知道，才开始玩

**Comment by Sicanus** [comment]
十分感谢！
