### ISSUE TITLE
正式版已出有计划吗？

### ISSUE THREAD

**Issue by z0z0r4** [ToadStudio/sakuranotoki_trail_chs#8]
如题qeq

**Comment by Sicanus** [comment]
正式版已经有不少汉化组占坑了，所以我个人大概是不会考虑做汉化了。再者，正式版的文本量和翻译难度都有点超出独立劳动的极限了，不如静候汉化组的佳音（虽然根据我的游玩体验，个人悲观估计精细汉化得1-2年起步，这个周期拿来自学日语都绰绰有余了）。
